backend:
  name: github
  repo: waynelan828/DafengWEB
  branch: main
  site_domain: nice8.work
  base_url: https://nice8.work # Your site domain

  auth_endpoint: /oauth

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'src/pages/about.astro'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'text' }
      - label: 'Contact Page'
        name: 'contact'
        file: 'src/pages/contact.astro'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'text' }
      - label: 'Privacy Policy'
        name: 'privacy'
        file: 'src/pages/privacy.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
