site:
  name: 大鋒木作工程
  site: 'https://nice8.works'
  base: '/'
  trailingSlash: false

  # Google Search Console 驗證碼（填入內容字串即可啟用 meta 驗證）
  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: 大鋒工程｜專業B2B木工工班
    template: '%s ｜大鋒工程'
  description: '設計師與屋主信賴的木工施工團隊，提供木作工程一站式整合，流程透明、工期嚴謹、品質保固。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 大鋒木作工程
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  language: zh-TW
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # 範例：G-XXXXXXXXXX，設定後自動載入 GA

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

